export enum AppView {
  DASHBOARD = 'DASHBOARD',
  INTERVIEW = 'INTERVIEW',
  FOCUS = 'FOCUS',
  ROADMAP = 'ROADMAP',
  INIT_PROFILE = 'INIT_PROFILE',
  MOCK_TEST = 'MOCK_TEST',
  ANALYTICS = 'ANALYTICS',
  DEV_MODE = 'DEV_MODE',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  PREDICTIVE = 'PREDICTIVE'
}
